name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Run CI in Dev Container
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/${{ github.repository }}/devcontainer
        cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
        push: never
        runCmd: |
          export CARGO_TERM_COLOR=always &&
          echo "::group::Check formatting" && cargo fmt --all -- --check && echo "::endgroup::" &&
          echo "::group::Build" && cargo build --verbose && echo "::endgroup::" &&
          echo "::group::Run tests" && cargo test --verbose && echo "::endgroup::" &&
          echo "::group::Run lints" && cargo clippy --all-targets -- -D warnings
