name: Pre-build Dev Container

on:
  workflow_dispatch:
  push:
    paths:
      - '.devcontainer/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'rust-toolchain.toml'
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Pre-build and push
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          cacheTo: ghcr.io/${{ github.repository }}/devcontainer
          push: filter
          refFilterForPush: refs/heads/main
          eventFilterForPush: push, workflow_dispatch
